import { library } from '@fortawesome/fontawesome-svg-core'

import {
    faArrowLeft,
    faBold,
    faCheck,
    faChevronDown,
    faChevronUp,
    faCode,
    faEye,
    faHeading,
    faImage,
    faItalic,
    faLink,
    faListOl,
    faListUl,
    faPlus,
    faQuoteLeft,
    faSpinnerThird,
    faTasks,
    faTimes,
    faTrash,
} from '@fortawesome/pro-light-svg-icons'

library.add(
    faTimes,
    faCheck,
    faSpinnerThird,
    faArrowLeft,
    faBold,
    faItalic,
    faHeading,
    faQuoteLeft,
    faListUl,
    faListOl,
    faLink,
    faImage,
    faEye,
    faPlus,
    faCode,
    faTasks,
    faCheck,
    faTimes,
    faChevronUp,
    faChevronDown,
    faTrash
)
